# Generated by Django 2.2.13 on 2020-08-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cveditor', '0003_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='list',
            field=models.TextField(default=''),
        ),
    ]
