# Generated by Django 2.2.13 on 2020-08-24 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cveditor', '0004_cv_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='list',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='text',
        ),
        migrations.AddField(
            model_name='item',
            name='cv',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cveditor.CV'),
        ),
    ]
