# Generated by Django 2.2.13 on 2020-08-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cveditor', '0006_auto_20200825_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='name',
            field=models.CharField(default='Name', max_length=200),
        ),
    ]
