# Generated by Django 2.2.13 on 2020-08-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cveditor', '0007_cv_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='address_line_1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cv',
            name='address_line_2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cv',
            name='address_line_3',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cv',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='phone',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='postcode',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cv',
            name='town',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cv',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
