# Generated by Django 2.2.13 on 2020-08-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cveditor', '0011_auto_20200826_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='academic_referee',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cv',
            name='academic_referee_contact_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='alevel_results',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='employment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='employment_referee',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cv',
            name='employment_referee_contact_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='gcse_results',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='modules_studied',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='personal_profile',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='school_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cv',
            name='sixth_form_or_college_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cv',
            name='skills_and_achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='university_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
